### ISSUE TITLE
animal_id missing from attributes

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#29]
The animal_id attribute is missing from the most recent example ncdump, can this please get added? 

This information is provided by researcher within the Reg App and represents a unique identifier for the tagged animal. There are cases no id is provided and then attribute should report 'not specified'

**Comment by mmckinzie** [comment]
@iamchrisser Can animal_id get added? Fine if listed in variables along with other animal attributes over being listed as a global attribute but it should get included somewhere.

**Comment by iamchrisser** [comment]
Yup, no problem. It's already in [the spreadsheet](https://docs.google.com/spreadsheets/d/1nYjpo5rF3W2qPV_XKva63g7VUv3Q659Z48ri9qXnF0g/edit#gid=0), but automating it's insertion into the netCDF files will take ADR work, so that'll have to wait until the next funding cycle. We can leave this open until then as a reminder.
