### ISSUE TITLE
citation attribute?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#31]
Is it possible to add a citation field as a global attribute? I know NCEI will generate a citation once these data are archived, but it would be good if that citation could be reported within the actual .nc files, particularly in cases where someone may pass off one of these archived data files to a colleague or collaborator for use over that researcher harvesting data themselves from directly NCEI. That way appropriate attribution is clear and does not get lost in the shuffle. Not sure if that is possible or recommended.

**Comment by MathewBiddle** [comment]
It's possible... But, this will be tricky. 

The citation NCEI provides will include the NCEI accession number. For example,
>Cite as: Cothran, Jeremy; Southeast Coastal Ocean Observing Regional Association (SECOORA) (2014). Oceanographic and surface meteorological data collected from station poncedeleonsouth by Florida Department of Environmental Protection (FLDEP) and assembled by Southeast Coastal Ocean Observing Regional Association (SECOORA) in the Coastal Waters of Florida and North Atlantic Ocean from 2014-02-13 to 2016-05-31 (NCEI Accession 0118775). [indicate subset used]. NOAA National Centers for Environmental Information. Dataset. https://www.ncei.noaa.gov/archive/accession/0118775. Accessed [date].

ATN won't know the accession number until the package has been archived at NCEI. So, if ATN provides a citation in the netCDF file, then NCEI provides a citation for the archived version, you will have two citations for the same dataset.

Bob Simons put together some guidance on [citing a dataset in ERDDAP](https://coastwatch.pfeg.noaa.gov/erddap/information.html#citeDataset) which could be helpful here. 

I think this is a good conversation to engage NCEI on.

**Comment by iamchrisser** [comment]
Compromise: we'll insert a citation into the citation attribute that's the same as the one NCEI will use, but without their accession number. We'll need to get the logic for composing the citation from John Relph.

**Comment by MathewBiddle** [comment]
Something for ATN to consider, providing citation guidance to users. I think you do this already

**Comment by iamchrisser** [comment]
We're waiting on the guidance from NCEI on building the citation. One thing that's going to be a problem is that since they're issuing the DOI, we'll not have that info to insert into the citaiton when we send them the data files. I guess we just build this internal citation without it?

**Comment by MathewBiddle** [comment]
I spoke with NCEI on wednesday and they should be sending it to you soon. Their citation is typically formatted as: 

`{AUTHORS}`;`{YEAR}`.`{TITLE}`.[indicate subset used] NOAA National Centers for Environmental Information. Dataset. `{ACCESS LINK}`. Accessed [date].

`{TITLE}` - This is the main piece of information you need from NCEI at the moment. I think the titles follow something like: 
> `{observation types}` collected from `{platform}` by `{collecting institution}` and assembled by `{assembly center}` in the `{sea names}` from `{start date}` to `{end date}` (NCEI Accession `{accession number}`)

`{ACCESS LINK}` - is either the ncei metadata landing page link, or the doi url.

So, yes the citation in the netCDF file will be missing the `{ACCESS LINK}` piece of information and the `{accession number}`. Those will be added by NCEI. 

My question is why is ATN trying to build the citation, instead of letting NCEI handle it?

As I stated above, my opinion would be to teach the ATN community where the appropriate citations can be found and how to use them.

**Comment by mmckinzie** [comment]
@MathewBiddle @iamchrisser  I still think including a citation attribute, if possible, using NCEI format is the best path forward. But if listed citation will lose key pieces of information (access link and accession number) bc those are generated by NCEI then maybe including a modified citation loses its purpose or usefulness.  ATN is not trying to dictate what the citation should be, just trying to make sure it readily available to future users both inside and outside of the ATN community, regardless of how these data are obtained. I also assume then that there is no way to list the DOI within the global attributes, either? 

It seems like maybe we need more discussion about this topic, so I proposed we wait to include the citation attribute, if we decide to do so until V2. Sound OK?

**Comment by MathewBiddle** [comment]
Yeah, I agree that this needs more discussion. 

Some jumbled thoughts:
* What is the frequency by which ATN will be archiving at NCEI?
   * I ask this because I'm trying to understand when a user will need to cite **open** data which hasn't yet made it to NCEI.
   * If NCEI checks ATN monthly, than, at most, it will be a month before a researcher can get a citation for the **open** data they might be using.
   * If data are embargoed - that's another thing and should have additional documentation. 
* The citation should always point to the archived version at NCEI. In whatever ATN data access tool (ATN portal, ERDDAP, etc.), we should be referring to the citation provided by NCEI as that is guaranteed for 75? years (plus we will have a DOI). This might require some updating of ATN data access _metadata_ once datasets are archived, but that's the right approach.

**Comment by mmckinzie** [comment]
ATN will be archiving data at NCEI, I believe, after individual deployments over individual project are out of embargo (~ 2 years after deployment end date, hopefully sooner). I thought this would happen on a deployment by deployment basis as needed, but maybe I flag deployments when ready and then we push data to NCEI one a month, for example. Something to discuss with Axiom. Only complete, non-embargoed datasets will get sent to NCEI. 

And yes Portal will link to the NCEI dataset, list provided DOIs once data are fully released .

**Comment by MathewBiddle** [comment]
somewhat related to
* https://github.com/cf-convention/cf-conventions/issues/160
