### ISSUE TITLE
information in dataset title 

### ISSUE THREAD

**Issue by iamchrisser** [ioos/ioos-atn-data#54]
On the most recent call we talked about adding the value of the `deployment_id` attribute to the title. This is captured in the [sparse notes from the call](https://docs.google.com/document/d/1nIBSPwA7ii5fnwIMdKlEHEpFgP_BAf7JVS4zHlPfIMM/edit#heading=h.5n3fdwi8ei3n). I think this was part of the talk about PTTs not being unique. 

Right now, the title is formatted like this:

> title: [common name] ([species]) location [and [parameter] profile] data from a deployed from [time_coverage_start] to [time_coverage_end] in the [sea_name], PTT [ptt].

Do we in fact want to do this? If so where do we want to add this information?

The deployment ID isn't something that we always have, and when we don't we fill the deploy_id variable with the ptt. I'll leave this out of the next template example I send along (we don't have a deployment ID for that deployment anyway).

**Comment by MathewBiddle** [comment]
I think Tim was interested in doing this, or at least was looking for more clarification as to what the ptt is. But, I think the time coverage components are enough to distinguish the packages uniqueness. 

I vote to leave the title as is, but punt to @mmckinzie for final decision.

**Comment by mmckinzie** [comment]
I think we should leave the ptt id in the title, but is it possible to list ptt id in parentheses after 'tag' instead? I think this placement better links this id to the tag, possibly adding some clarification and then we could list the deployment id at the end of the title as this id encompasses the whole statement, if we wish to include a unique identifier. 

Every deployment does have a unique deployment id, including this recent loggerhead example.  Some older projects/deployments may presently be missing them from Reg App but they exist and will be included prior to release to NCEI.    

I am also thinking it's best to list the actual deployment window in title, i.e., the deployment_start_datetime and deployment_end_datatime instead of the date range associated with data file itself (i.e., time_coverage_start and time_coverage_end). The recent loggerhead example illustrates this point nicely as tag was deployed 2000-07-14 to 2001-07-24 but date file range is 1999-07-20 to 2004-02-26. 

Can we also list 'satellite telemetry tag' instead of just tag? And place sea name before date range? 

So... list title as:    

title: [common name] ([species]) location data from a [instrument] (ptt id [ptt id]) deployed in the [sea_name] from [deployment_start_datetime] to [deployment_end_datetime], deployment id [deployment id].

e.g., Loggerhead turtle (Caretta caretta) location data from a satellite telemetry tag (ptt id 22275) deployed in the North Atlantic Ocean from 2000-07-17 to 2001-07-24, deployment id 5f08ee316321be13bc7fbc37.

**Comment by iamchrisser** [comment]
This is a very along title, but I don't have any problem with it if the NCEI folks don't mind.
